
project_id = "xcpwyvrlutlslgaueokd"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324

[storage]
port = 54325

[auth]
port = 54326

[realtime]
port = 54327

[functions]
port = 54328
[functions.api-proxy]
verify_jwt = false
