
project_id = "xcpwyvrlutlslgaueokd"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324

[storage]
enabled = true

[auth]
enabled = true

[realtime]
enabled = true

[analytics]
enabled = false
port = 54327

[vector]
enabled = false
port = 54328

[functions.api-proxy]
verify_jwt = false

[functions.order-api]
verify_jwt = false

[functions.product-sync]
verify_jwt = false

[functions.scheduled-sync]
verify_jwt = false
