
project_id = "xcpwyvrlutlslgaueokd"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322
shadow_port = 54320

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[realtime]
enabled = false

[auth]
enabled = true

[functions]
[functions.product-sync]
verify_jwt = false
[functions.order-api]
verify_jwt = false
[functions.scheduled-sync]
verify_jwt = false

