
project_id = "xcpwyvrlutlslgaueokd"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324

[storage]
enabled = true

[auth]
enabled = true

[realtime]
enabled = true

[functions]
[functions.syncProductFromTaphoammo]
verify_jwt = true

[functions.auth-redirect]
verify_jwt = false

